import type { Metadata } from "next";
import localFont from "next/font/local";
import "./global.css";

const inter = localFont({
  src: "./fonts/InterVF.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700 800 900",
});

const spaceGrotesk = localFont({
  src: "./fonts/SpaceGroteskVF.ttf",
  variable: "--font-space-grotesk",
  weight: "100 200 300 400 500 600 700 800 900",
});

const notoKufiAarabic = localFont({
  src: "./fonts/NotoKufiArabicVF.ttf",
  variable: "--font-noto-kufi-arabic",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "NEWDZ ARTICLES",
  description: "Generated by create next app",
};

const GlobalLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${spaceGrotesk.variable} ${notoKufiAarabic.variable}`}
      >
        <h1>Hello</h1>
        {children}
      </body>
    </html>
  );
};

export default GlobalLayout;
